version: "3.8"

services:
  frontend-tests:
    build:
      context: ./blipay-interface
      dockerfile: Dockerfile.test
    container_name: frontend-tests
    command: npm run test-docker
#docker compose -f docker-compose-frontend.test.yml up --abort-on-container-exit --exit-code-from frontend-tests
