version: "3.8"

services:
  backend-tests:
    build:
      context: ./blipay-backend/blipay
      dockerfile: Dockerfile.test
    volumes:
      - "./blipay-backend/:/home/project/blipay"
    container_name: backend-tests
#docker compose -f docker-compose-backend.test.yml up --abort-on-container-exit --exit-code-from backend-tests
