version: "3.8"

services:
  api:
    build: ./blipay-backend/blipay
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 index:app --timeout 3600
    # restart: unless-stopped
    volumes:
      - "./blipay-backend/:/home/project/blipay"
    #ports:
    #- 5000:5000

  nginx:
    build: ./blipay-interface
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
