FROM python:3.13-alpine

WORKDIR /home/project/blipay
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install pytest pytest-cov

CMD ["pytest", "--cov=.", "--cov-report=term-missing"]
